services:
  web:
    build: .
    ports:
      - "8081:8080"
    depends_on:
      db:
        condition: service_healthy
    restart: always

  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=cyclek
    volumes:
      - ./src/main/database/cyclek.sql:/docker-entrypoint-initdb.d/init.sql
      - ./docker/data/db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 10s
      retries: 50
    restart: always