services:
  web:
    image: tomcat:10
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./target/cycleK-1-0-0.war:/usr/local/tomcat/webapps/cycleK-1-0-0.war
      - ./src/main/resources/tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml
      
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    volumes:
      - ./src/main/database/cyclek.sql:/docker-entrypoint-initdb.d/init.sql
      - ./docker/data/db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 10s
      retries: 50